### ISSUE TITLE
www.lava-nc.org leads to nowhere

### ISSUE THREAD

**Issue by Tobias-Fischer** [lava-nc/lava-nc.github.io#3]
While one can open https://lava-nc.org without issues, www.lava-nc.org does not load. The GitHub organisation page (https://github.com/lava-nc) currently points to the non-working www.lava-nc.org

**Comment by mgkwill** [comment]
Thanks for pointing this out Tobias. There was a transfer of domain
registration recently, in the process they must have forgot to create a DNS
CNAME record for www.

I’ll check into it.

**Comment by mgkwill** [comment]
I've submitted a request to fix this. As soon as it is approved it will be working.

Hopefully some time today.

**Comment by mgkwill** [comment]
This is now fixed www.lava-nc.org should be working.
